# Generated by Django 5.1.4 on 2024-12-26 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('detail', models.CharField(max_length=45)),
                ('organizer', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('stage_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.stage_event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('customer', models.CharField(max_length=45)),
                ('no_of_seats', models.IntegerField()),
                ('stage_event_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.show')),
            ],
        ),
    ]
